In [138]:
import pandas as pd
import datetime
!pip install datetime_truncate
from datetime_truncate import truncate
import numpy as np
import math

Requirement already satisfied: datetime_truncate in c:\users\mateg\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: six in c:\users\mateg\anaconda3\lib\site-packages (from datetime_truncate) (1.12.0)
Requirement already satisfied: typing in c:\users\mateg\anaconda3\lib\site-packages (from datetime_truncate) (3.7.4.1)

In [139]:
data = pd.read_csv("../data/Suicide_withDBPedia_Values_fr.csv", sep=";", encoding='utf-8-sig')
data.head()

,Name,Link,Content,abstract,birthdate,birthplace_clean,birthplace,deathdate,deathplace_clean,deathplace,gender,birthCountry,birthcountry
0,Adolfo_Couve,https://fr.wikipedia.org/wiki/Adolfo_Couve,"['id=""Biographie"">Biographie[modifier', '|', '...","Adolfo Couve Rioseco (Valparaíso, 28 de marzo ...",1940-3-28,Valparaíso,http://dbpedia.org/resource/Valparaíso,1998-3-11,"Cartagena,_Chile","http://dbpedia.org/resource/Cartagena,_Chile",male,Chile,Chile
1,Ralph_Barton,https://fr.wikipedia.org/wiki/Ralph_Barton,"['id=""Biographie"">Biographie[modifier', '|', '...",Ralph Waldo Emerson Barton (14 août 1891 – 19 ...,1891-8-14,"Kansas_City,_Missouri","http://dbpedia.org/resource/Kansas_City,_Missouri",1931-5-19,"New_York_City,_New_York","http://dbpedia.org/resource/New_York_City,_New...",male,United_States,United_States
2,Jack_Goldstein,https://fr.wikipedia.org/wiki/Jack_Goldstein,[],Jack Goldstein (* 27. September 1945 in Montre...,1945-9-27,Montreal,http://dbpedia.org/resource/Montreal,2003-3-14,"San_Bernardino,_California","http://dbpedia.org/resource/San_Bernardino,_Ca...",male,Canada,Canada
3,Paul_Markwitz,https://fr.wikipedia.org/wiki/Paul_Markwitz,"['id=""Biographie"">Biographie[modifier', '|', '...",Paul E. Markwitz (* 16. Juli 1908 in Berlin; †...,1908-7-16,Berlin,http://dbpedia.org/resource/Berlin,1968-03-19,Berlin,http://dbpedia.org/resource/Berlin,male,Germany,Germany
4,Virginia_Woolf,https://fr.wikipedia.org/wiki/Virginia_Woolf,"['id=""Biographie"">Biographie[modifier', '|', '...",Adeline Virginia Woolf (née Stephen; 25 Januar...,1882-01-25,Kensington,http://dbpedia.org/resource/Kensington,1941-03-28,Lewes,http://dbpedia.org/resource/Lewes,female,United_Kingdom,United_Kingdom

## List all values in birthCountry to know which ones need to be changed

In [140]:
birthCountry = data["birthCountry"]
birthCountry.unique()

array(['Chile', 'United_States', 'Canada', 'Germany', 'United_Kingdom',
       'Tunisia', nan, 'United_States_of_America', 'Mexico', 'Russia',
       'France', 'Bosnia_and_Herzegovina', 'Spain', 'Austria', 'England',
       'Switzerland', 'Japan', 'Belarus', 'Hungary', 'Italy', 'Denmark',
       'Netherlands', 'Belgium', 'Poland', 'India', 'South_Korea',
       'China', 'Sweden', 'Israel', 'Venezuela', 'Myanmar', 'Australia',
       'Serbia', 'Czech_Republic', 'Ukraine', 'Brazil', 'Kent',
       'Bulgaria', 'South_Africa', 'Iran', 'Peru', 'Romania', 'Portugal',
       'Essex', 'Argentina', 'Slovakia', 'Scotland', 'Macedonia',
       'Norway', 'Latvia', 'Cuba', 'Kosovo', 'Lithuania', 'Palau',
       'Estonia', 'Georgia_(country)', 'Egypt', 'Ethiopia', 'Turkey',
       'Republic_of_Ireland', 'Kazakhstan', 'Ulster', 'Northern_Ireland',
       'Moldova', 'Uruguay', 'Lebanon', 'Colombia', 'Suffolk', 'Taiwan'],
      dtype=object)

## Replacing values

In [141]:
for i in range(len(data)):
    if (birthCountry[i]=="United_States_of_America" or birthCountry[i] == "Essex" or birthCountry[i] == "Ulster" or birthCountry[i] == "Suffolk" or birthCountry[i] == "United_States"):
        birthCountry[i] = "USA"
    elif(birthCountry[i] == "Kent" or birthCountry[i] == "United_Kingdom"):
        birthCountry[i] = "UK"
    elif(birthCountry[i] == "Georgia_(country)"):
        birthCountry[i] = "Georgia"
    elif(birthCountry[i] == "Republic_of_Ireland" or birthCountry[i] == "Northern_Ireland"):
        birthCountry[i] = "Ireland"

In [142]:
data["birthCountry"] = birthCountry

## Deleting the ones for who the deathdate is incorrect

For those ones, it is because they were dead before the 17th century.

In [143]:
data = data[data["Name"] != "Xiang_Yu"]
data = data[data["Name"] != "Quintillus"]
data = data[data["Name"] != "Wei_Zhongxian"]
data = data[data["Name"] != "Francesco_Borromini"]
data = data[data["Name"] != "Qin_Er_Shi"]
data = data[data["Name"] != "Bartolomeo_Schedoni"]
data = data[data["Name"] != "Uriel_da_Costa"]
data = data[data["Name"] != "Joseph_Newton_Chandler_III"]
data = data[data["Name"] != "Qu_Yuan"]
data = data[data["Name"] != "Chimalpopoca"]
data = data[data["Name"] != "François_Vatel"]
data = data[data["Name"] != "Hōjō_Ujimasa"]
data = data[data["Name"] != "Oda_Nobunaga"]
data = data[data["Name"] != "Oda_Nobutada"]
data = data[data["Name"] != "Ōuchi_Yoshitaka"]
data = data[data["Name"] != "Sen_no_Rikyū"]
data = data[data["Name"] != "Shibata_Katsuie"]

In [144]:

dateDeathTimestamp = []
for i in range(len(data)):
    dateDeathTimestamp.append(pd.Timestamp(data["deathdate"].values[i])) #convert into timestamp
    dateDeathTimestamp[i] = truncate(dateDeathTimestamp[i], 'year') # trunc to years

In [145]:
deathDateCountry = pd.DataFrame()
deathDateCountry["deathdate"] = dateDeathTimestamp
Ones = np.ones(len(deathDateCountry))
deathDateCountry["Country"] = data["birthCountry"]
deathDateCountry["Ones"] = Ones
deathDateCountry = deathDateCountry.dropna()
deathDateCountry.head()

   deathdate  Country  Ones
0 1998-01-01    Chile   1.0
1 1931-01-01      USA   1.0
2 2003-01-01   Canada   1.0
3 1968-01-01  Germany   1.0
4 1941-01-01       UK   1.0

In [146]:
grouped_deathDateCountry = deathDateCountry.groupby(["Country", "deathdate"]).sum().reset_index()

In [147]:
grouped_deathDateCountry.head()

     Country  deathdate  Ones
0  Argentina 1931-01-01   1.0
1  Argentina 1933-01-01   1.0
2  Argentina 1938-01-01   1.0
3  Argentina 1973-01-01   1.0
4  Argentina 1975-01-01   1.0

In [148]:
nb = [0]*len(grouped_deathDateCountry)
current_nb = 1
for i in range(len(grouped_deathDateCountry)):
    if (i > 0):
        if(grouped_deathDateCountry["Country"].values[i] == grouped_deathDateCountry["Country"].values[i-1]):
            current_nb += grouped_deathDateCountry["Ones"].values[i]
            nb[i] = current_nb
        else:
            current_nb = grouped_deathDateCountry["Ones"].values[i]

In [149]:
grouped_deathDateCountry["Count"] = nb
grouped_deathDateCountry.head()

     Country  deathdate  Ones  Count
0  Argentina 1931-01-01   1.0    0.0
1  Argentina 1933-01-01   1.0    2.0
2  Argentina 1938-01-01   1.0    3.0
3  Argentina 1973-01-01   1.0    4.0
4  Argentina 1975-01-01   1.0    5.0

In [150]:
data_pivot = grouped_deathDateCountry.pivot_table("Count", "Country", "deathdate")
data_pivot = data_pivot.fillna(0)
data_pivot.head()

deathdate,1692-01-01 00:00:00,1701-01-01 00:00:00,1707-01-01 00:00:00,1735-01-01 00:00:00,1737-01-01 00:00:00,1774-01-01 00:00:00,1791-01-01 00:00:00,1794-01-01 00:00:00,1795-01-01 00:00:00,1797-01-01 00:00:00,...,2009-01-01 00:00:00,2010-01-01 00:00:00,2011-01-01 00:00:00,2012-01-01 00:00:00,2013-01-01 00:00:00,2014-01-01 00:00:00,2015-01-01 00:00:00,2016-01-01 00:00:00,2038-01-01 00:00:00,2066-01-01 00:00:00
Country,,,,,,,,,,,,,,,,,,,,,
Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Australia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0
Austria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,27.0,28.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0
Belarus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Belgium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,7.0,0.0,0.0,8.0,0.0,0.0

In [151]:
data_pivot = data_pivot.iloc[:, 129:-2]
data_pivot = data_pivot.cumsum(axis=1)
total = data_pivot.sum(axis=0).T
data_pivot = (data_pivot / total)*100
data_pivot = data_pivot.reset_index()
data_pivot

deathdate,Country,1979-01-01 00:00:00,1980-01-01 00:00:00,1981-01-01 00:00:00,1982-01-01 00:00:00,1983-01-01 00:00:00,1984-01-01 00:00:00,1985-01-01 00:00:00,1986-01-01 00:00:00,1987-01-01 00:00:00,...,2007-01-01 00:00:00,2008-01-01 00:00:00,2009-01-01 00:00:00,2010-01-01 00:00:00,2011-01-01 00:00:00,2012-01-01 00:00:00,2013-01-01 00:00:00,2014-01-01 00:00:00,2015-01-01 00:00:00,2016-01-01 00:00:00
0,Argentina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Australia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.163739,0.155565,0.147354,0.141279,0.137311,0.133059,0.195425,0.191183,0.185145,0.181527
2,Austria,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.386263,1.282051,1.268743,...,1.786246,1.697073,1.607502,1.888004,2.184496,2.116850,2.011725,1.968061,2.221738,2.178324
3,Belarus,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Belgium,0.000000,0.000000,0.378310,0.309278,0.262467,0.226415,0.189036,0.174825,0.173010,...,0.104198,0.098996,0.160750,0.154123,0.149794,0.145155,0.218416,0.213675,0.206927,0.288308
5,Bosnia_and_Herzegovina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.074427,0.070711,0.066979,0.115592,0.112346,0.108867,0.103460,0.101215,0.098018,0.096103
6,Brazil,0.000000,0.000000,0.000000,0.000000,0.262467,0.226415,0.189036,0.174825,0.173010,...,0.267937,0.254561,0.241125,0.231184,0.224691,0.217733,0.206920,0.202429,0.196036,0.192205
7,Bulgaria,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Canada,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.757576,0.749712,...,0.863352,0.820252,1.004689,0.963267,0.936213,0.907221,0.862168,0.843455,0.816816,0.800854
9,Chile,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059542,0.056569,0.120563,0.115592,0.112346,0.108867,0.103460,0.101215,0.098018,0.096103
10,China,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,Colombia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Cuba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,Czech_Republic,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.163739,0.155565,0.147354,0.141279,0.299588,0.290311,0.275894,0.269906,0.261381,0.256273
14,Denmark,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,Egypt,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,England,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.133968,0.127280,0.120563,0.115592,0.112346,0.108867,0.103460,0.101215,0.098018,0.096103
17,Estonia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.029771,0.028285,0.026792,0.025687,0.062414,0.060481,0.057478,0.056230,0.054454,0.053390
18,Ethiopia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,France,28.294574,27.631579,27.994956,31.134021,33.683290,35.396226,35.034657,37.587413,37.197232,...,30.202441,30.236176,30.127261,28.885179,29.484459,28.571429,28.463042,27.845254,28.218253,27.666845
20,Georgia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.025687,0.024966,0.024193,0.022991,0.022492,0.021782,0.021356
21,Germany,30.620155,29.887218,30.264817,24.742268,28.171479,24.301887,20.289855,18.764569,18.569781,...,15.317059,15.881771,15.043537,15.643463,15.204094,14.733277,15.116680,14.788574,15.388804,15.088094
22,Hungary,0.000000,0.000000,0.000000,0.000000,0.437445,0.377358,0.315060,0.291375,0.288351,...,0.074427,0.070711,0.066979,0.064218,0.062414,0.133059,0.126451,0.123707,0.119800,0.117459
23,India,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.021356
24,Iran,0.000000,0.000000,0.000000,0.206186,0.174978,0.150943,0.126024,0.116550,0.115340,...,0.074427,0.070711,0.066979,0.064218,0.062414,0.060481,0.057478,0.056230,0.054454,0.053390
25,Ireland,0.000000,0.000000,0.504414,0.412371,0.349956,0.301887,0.252048,0.233100,0.230681,...,0.133968,0.127280,0.120563,0.115592,0.112346,0.108867,0.103460,0.101215,0.098018,0.096103
26,Israel,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,Italy,6.589147,3.195489,2.143758,1.752577,1.487314,1.283019,1.071204,0.990676,2.018454,...,1.741590,1.654646,1.567314,1.502697,1.460492,1.705576,1.908265,1.866847,1.807885,1.772557
28,Japan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.134216,2.156177,2.133795,...,1.161060,1.103097,1.339585,1.284357,1.535389,1.778154,1.977239,2.226721,2.156393,2.114255
29,Kazakhstan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,Lebanon,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,Lithuania,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,Macedonia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,Mexico,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,Moldova,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,Myanmar,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,Netherlands,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.089969,0.087127,0.085424
39,Norway,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,Palau,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,Peru,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,Poland,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.041977,0.989959,1.219022,1.168764,1.410560,1.366880,1.299000,1.270805,1.230669,1.206620
43,Portugal,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.049931,0.048385,0.045982,0.044984,0.043563,0.042712
44,Romania,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.060481,0.057478,0.056230,0.054454,0.053390
45,Russia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.119083,0.113138,0.107167,0.102749,0.099863,0.096770,0.091965,0.089969,0.087127,0.085424
46,Scotland,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.029771,0.028285,0.026792,0.025687,0.024966,0.024193,0.022991,0.022492,0.021782,0.021356
47,Serbia,0.000000,0.000000,0.000000,0.000000,0.000000,0.150943,0.126024,0.116550,0.115340,...,0.029771,0.028285,0.026792,0.025687,0.062414,0.060481,0.057478,0.056230,0.054454,0.053390
48,Slovakia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059542,0.056569,0.053583,0.051374,0.049931,0.048385,0.045982,0.044984,0.043563,0.042712
49,South_Africa,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.104198,0.098996,0.093771,0.089905,0.087380,0.084674,0.080469,0.078722,0.076236,0.074746
50,South_Korea,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.028285,0.026792,0.025687,0.062414,0.060481,0.057478,0.056230,0.054454,0.053390
51,Spain,0.000000,0.000000,0.630517,0.515464,0.437445,0.377358,0.693132,0.641026,0.634371,...,0.520988,0.494979,0.468855,0.449525,0.436899,0.423370,0.402345,0.393612,0.381181,0.373732
52,Sweden,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.466200,0.461361,...,0.565645,0.537406,0.669792,0.642178,0.624142,0.604814,0.574779,0.562303,0.544544,0.672718
53,Switzerland,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.312593,0.296988,0.442063,0.423838,0.574210,0.556429,0.528796,0.517319,0.500980,0.491191
54,Taiwan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55,Tunisia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,Turkey,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.029771,0.028285,0.026792,0.025687,0.024966,0.024193,0.022991,0.022492,0.021782,0.021356
57,UK,0.000000,5.639098,3.783102,3.092784,2.624672,2.264151,3.843730,3.554779,3.517878,...,3.989283,3.790129,4.099129,4.431030,4.306578,4.657070,4.425796,4.329735,4.639512,4.548852
58,USA,34.496124,33.646617,34.300126,37.835052,32.108486,34.943396,35.349716,32.692308,32.352941,...,40.756177,40.814595,40.683188,40.983817,39.832730,40.498367,40.303483,41.216824,39.915051,40.843566
59,Ukraine,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.089312,0.084854,0.080375,0.077061,0.074897,0.072578,0.068973,0.067476,0.141581,0.138815
60,Uruguay,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
61,Venezuela,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [152]:
data_pivot.to_csv('../data/Dataframe_for_racing_plot.csv', sep=',', encoding='utf-8-sig', index=False)

# RACING PLOT FOR WHO DATA

In [153]:
data = pd.read_csv("../data/who_suicide_statistics.csv", sep=",", encoding='utf-8-sig')
data.head()

   country  year     sex          age  suicides_no  population
0  Albania  1985  female  15-24 years          NaN    277900.0
1  Albania  1985  female  25-34 years          NaN    246800.0
2  Albania  1985  female  35-54 years          NaN    267500.0
3  Albania  1985  female   5-14 years          NaN    298300.0
4  Albania  1985  female  55-74 years          NaN    138700.0

In [154]:
data = data.dropna()
data.head()

    country  year     sex          age  suicides_no  population
24  Albania  1987  female  15-24 years         14.0    289700.0
25  Albania  1987  female  25-34 years          4.0    257200.0
26  Albania  1987  female  35-54 years          6.0    278800.0
27  Albania  1987  female   5-14 years          0.0    311000.0
28  Albania  1987  female  55-74 years          0.0    144600.0

In [155]:
data = data.drop(["age", "population"], axis=1).groupby(["year", "country"]).sum().reset_index()
data.head()

   year    country  suicides_no
0  1979  Argentina       1802.0
1  1979  Australia       1675.0
2  1979   Barbados          2.0
3  1979    Belgium       2114.0
4  1979     Brazil       3459.0

In [156]:
data = data.pivot(index = "country", columns = "year", values ="suicides_no").fillna(0)

In [157]:
data.head()

year,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
country,,,,,,,,,,,,,,,,,,,,,
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73.0,63.0,...,124.0,160.0,0.0,96.0,0.0,0.0,0.0,0.0,0.0,0.0
Antigua and Barbuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Argentina,1802.0,1972.0,2197.0,1965.0,1834.0,1873.0,1988.0,2284.0,2286.0,2354.0,...,2946.0,3059.0,2884.0,2943.0,2912.0,3248.0,2987.0,3231.0,3073.0,0.0
Armenia,0.0,0.0,92.0,70.0,0.0,0.0,74.0,61.0,81.0,61.0,...,71.0,63.0,53.0,73.0,67.0,79.0,67.0,58.0,74.0,67.0
Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,4.0,4.0,7.0,9.0,3.0,2.0,5.0,9.0,0.0

In [158]:
data = data.cumsum(axis=1)
total = data.sum(axis=0).T
data = (data / total)*100
data = data.reset_index()
data.head()

year,country,1979,1980,1981,1982,1983,1984,1985,1986,1987,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Albania,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005125,...,0.028002,0.029469,0.028370,0.028771,0.027801,0.026916,0.026102,0.025339,0.024680,0.024630
1,Antigua and Barbuda,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000163,0.000157,0.000151,0.000146,0.000141,0.000137,0.000132,0.000129,0.000138,0.000138
2,Argentina,1.94202,1.532962,1.408604,1.308858,1.341119,1.365331,1.298345,1.284961,1.277877,...,1.135833,1.141384,1.142481,1.145163,1.147626,1.155495,1.160113,1.167764,1.175887,1.173500
3,Armenia,0.00000,0.000000,0.021703,0.026718,0.022238,0.018997,0.022479,0.023979,0.026539,...,0.029750,0.029626,0.029324,0.029355,0.029311,0.029457,0.029454,0.029339,0.029503,0.030281
4,Aruba,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001258,0.001274,0.001287,0.001344,0.001425,0.001421,0.001404,0.001428,0.001503,0.001500

In [159]:
data.head(200)

year,country,1979,1980,1981,1982,1983,1984,1985,1986,1987,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Albania,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005125,...,0.028002,0.029469,0.028370,0.028771,0.027801,0.026916,0.026102,0.025339,0.024680,0.024630
1,Antigua and Barbuda,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000163,0.000157,0.000151,0.000146,0.000141,0.000137,0.000132,0.000129,0.000138,0.000138
2,Argentina,1.942020,1.532962,1.408604,1.308858,1.341119,1.365331,1.298345,1.284961,1.277877,...,1.135833,1.141384,1.142481,1.145163,1.147626,1.155495,1.160113,1.167764,1.175887,1.173500
3,Armenia,0.000000,0.000000,0.021703,0.026718,0.022238,0.018997,0.022479,0.023979,0.026539,...,0.029750,0.029626,0.029324,0.029355,0.029311,0.029457,0.029454,0.029339,0.029503,0.030281
4,Aruba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001258,0.001274,0.001287,0.001344,0.001425,0.001421,0.001404,0.001428,0.001503,0.001500
5,Australia,1.805151,1.332711,1.168214,1.107978,1.155120,1.192364,1.145755,1.136240,1.139986,...,0.975044,0.975328,0.974337,0.975312,0.976166,0.980363,0.985258,0.993646,1.005722,1.003680
6,Austria,0.000000,0.784760,0.935137,0.995168,1.108448,1.184741,1.161472,1.157232,1.151570,...,0.796365,0.786455,0.776475,0.767546,0.759830,0.753092,0.747413,0.742469,0.738829,0.752382
7,Azerbaijan,0.000000,0.000000,0.067705,0.086751,0.072204,0.061682,0.073342,0.081143,0.088393,...,0.054990,0.052930,0.050957,0.049159,0.047501,0.045990,0.044598,0.043295,0.042169,0.042083
8,Bahamas,0.000000,0.000406,0.000472,0.000330,0.000961,0.001642,0.001429,0.001211,0.001264,...,0.001193,0.001211,0.001257,0.001358,0.001369,0.001394,0.001418,0.001376,0.001340,0.001338
9,Bahrain,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001048,0.000888,0.001404,...,0.005130,0.005614,0.005949,0.006017,0.006068,0.006135,0.006015,0.005955,0.005800,0.005789
10,Barbados,0.002155,0.002031,0.002831,0.002309,0.003157,0.003283,0.003334,0.003472,0.003440,...,0.003202,0.003098,0.003058,0.002994,0.002893,0.002801,0.002716,0.002637,0.002568,0.002563
11,Belarus,0.000000,0.000000,0.563347,0.825293,0.686895,0.586801,0.695892,0.733352,0.772581,...,1.001444,1.005724,1.009746,1.010041,1.006619,0.974597,0.970312,0.964345,0.939261,0.937355
12,Belgium,2.278263,1.743369,1.521367,1.418699,1.489095,1.546391,1.473318,1.426658,1.397724,...,0.982640,0.977262,0.971294,0.966432,0.963296,0.960333,0.956387,0.952859,0.951464,0.949532
13,Belize,0.000000,0.000812,0.000472,0.000330,0.000275,0.000469,0.000381,0.000565,0.000772,...,0.003153,0.003208,0.003315,0.003417,0.003768,0.003894,0.004001,0.004193,0.004410,0.004401
14,Bermuda,0.000000,0.001219,0.000708,0.000495,0.000824,0.000704,0.000571,0.000484,0.000421,...,0.000098,0.000094,0.000091,0.000088,0.000085,0.000082,0.000079,0.000077,0.000075,0.000075
15,Bosnia and Herzegovina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.041243,0.075329,0.099135,...,0.053471,0.051468,0.049549,0.047801,0.046259,0.044787,0.043432,0.046189,0.044987,0.044896
16,Brazil,3.727772,2.974532,2.678022,2.514967,2.719438,2.839134,2.708799,2.640972,2.624558,...,2.784501,2.824604,2.860760,2.897558,2.938418,2.985602,3.034568,3.082614,3.142280,3.135901
17,Brunei Darussalam,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001274,0.001368,0.001347,0.001373,0.001397,0.001462,0.001471,0.001492,0.001541,0.001538
18,Bulgaria,0.000000,0.489866,0.569717,0.622598,0.682090,0.759886,0.755900,0.754425,0.760786,...,0.606464,0.598509,0.589331,0.581089,0.572254,0.565963,0.558393,0.551385,0.537043,0.535953
19,Cabo Verde,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000593,0.000574,0.000556,0.000540,0.000526,0.000525
20,Canada,3.615691,2.725537,2.385025,2.247456,2.386012,2.441601,2.293511,2.240426,2.200354,...,1.717480,1.711399,1.706471,1.703980,1.699107,1.698696,1.701017,1.651300,1.608348,1.605083
21,Cayman Islands,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,Chile,0.000000,0.218937,0.280494,0.302640,0.342486,0.378887,0.372806,0.368816,0.369370,...,0.468154,0.483450,0.497939,0.509599,0.521013,0.529592,0.536598,0.543925,0.552803,0.551681
23,Colombia,0.000000,0.000000,0.000000,0.000000,0.000000,0.123833,0.195928,0.243428,0.278449,...,0.602363,0.614706,0.625831,0.634527,0.641967,0.650496,0.658216,0.666323,0.678207,0.676830
24,Costa Rica,0.000000,0.049555,0.051664,0.050962,0.060536,0.064966,0.064960,0.065641,0.065435,...,0.086570,0.087431,0.088379,0.089804,0.091234,0.092458,0.093781,0.094487,0.092029,0.091843
25,Croatia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100012,0.168987,0.227899,...,0.371292,0.369852,0.368020,0.366372,0.363919,0.362944,0.361133,0.359864,0.359762,0.367570
26,Cuba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.482253,0.485840,0.490083,0.495550,0.500410,0.504917,0.509502,0.513300,0.518878,0.517824
27,Cyprus,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001144,0.001745,0.002165,0.002643,0.002978,0.003375,0.003869,0.004322,0.004710,0.005151
28,Czech Republic,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.174881,0.287998,...,0.625709,0.623952,0.622848,0.622814,0.624242,0.627037,0.628961,0.629730,0.630726,0.645924
29,Denmark,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.170820,0.173903,0.176834,0.178819,0.181099,0.184369,0.186873,0.189502,0.191638,0.191249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Russian Federation,0.000000,19.447175,22.513594,23.765441,19.780067,16.897720,17.965377,17.911379,17.951424,...,20.432294,20.267706,20.078230,19.857152,19.625291,19.405981,19.199000,18.979235,18.804171,18.765996
89,Saint Kitts and Nevis,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
90,Saint Lucia,0.001078,0.001625,0.001180,0.000825,0.001922,0.001642,0.001333,0.001534,0.002106,...,0.002957,0.002846,0.002937,0.002892,0.002907,0.002951,0.003047,0.003138,0.003057,0.003051
91,Saint Vincent and Grenadines,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000190,0.000161,0.000140,...,0.001536,0.001541,0.001499,0.001519,0.001538,0.001626,0.001577,0.001556,0.001553,0.001550
92,San Marino,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000343,0.000330,0.000318,0.000307,0.000296,0.000287,0.000278,0.000270,0.000263,0.000263
93,Sao Tome and Principe,0.000000,0.000000,0.000000,0.000000,0.000000,0.000117,0.000286,0.000242,0.000281,...,0.000065,0.000063,0.000061,0.000058,0.000056,0.000055,0.000053,0.000051,0.000050,0.000050
94,Serbia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.235547,0.246993,0.258568,0.267075,0.275790,0.283999,0.291267,0.297340,0.302910,0.302295
95,Seychelles,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000762,0.000727,0.000843,...,0.000915,0.000944,0.000969,0.001022,0.001058,0.001066,0.001153,0.001170,0.001228,0.001225
96,Singapore,0.265115,0.209188,0.166315,0.155526,0.166096,0.166635,0.166210,0.167210,0.166536,...,0.143848,0.143475,0.143408,0.142673,0.142206,0.143038,0.143441,0.143814,0.144195,0.143903
97,Slovakia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.161296,0.164546,0.167509,0.170816,0.165053,0.167604,0.170695,0.172832,0.168336,0.167995
98,Slovenia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.061626,0.100359,0.130659,...,0.218998,0.217209,0.215877,0.214308,0.213217,0.212446,0.211928,0.210725,0.210530,0.210103
99,South Africa,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059156,0.063875,0.067125,0.070497,0.073170,0.077497,0.082930,0.087966,0.091716,0.091530
100,Spain,0.000000,0.671026,0.795008,0.861082,1.016066,1.160350,1.181950,1.224326,1.261518,...,1.338755,1.342962,1.344794,1.343480,1.343034,1.348663,1.359176,1.369755,1.379276,1.376476
101,Sri Lanka,0.000000,1.734027,2.045318,2.267082,2.654373,2.944087,2.931206,2.916212,2.535884,...,1.319167,1.269747,1.222398,1.179280,1.139498,1.103248,1.069870,1.038600,1.011585,1.009531
102,Suriname,0.052807,0.043462,0.037509,0.036779,0.030611,0.038229,0.038671,0.036171,0.035105,...,0.025469,0.026827,0.027810,0.028815,0.029635,0.030510,0.031322,0.032053,0.031219,0.031156
103,Sweden,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.108192,...,0.445772,0.447471,0.449587,0.450392,0.450891,0.452314,0.454927,0.456396,0.459333,0.472591
104,Switzerland,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.286617,0.296542,0.302212,0.306244,0.310505,0.314810,0.319476,0.323412,0.328442,0.327775
105,TFYR Macedonia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.041774,0.042741,0.043675,0.043916,0.044241,0.045184,0.046069,0.044723,0.043559,0.043471
106,Thailand,3.283759,2.621959,2.326048,2.152458,2.231447,2.256438,2.116823,2.020251,1.969858,...,1.543295,1.544887,1.544609,1.545053,1.547587,1.552802,1.558305,1.563591,1.575600,1.624049
107,Trinidad and Tobago,0.059274,0.039807,0.036802,0.038593,0.045711,0.047845,0.041624,0.043680,0.046338,...,0.062424,0.063215,0.062795,0.062917,0.062756,0.060759,0.058921,0.057199,0.055711,0.055598
108,Turkey,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.015896,0.037592,0.052525,0.070665,0.092509,0.110604,0.126919,0.126662
109,Turkmenistan,0.000000,0.000000,0.061336,0.079989,0.066576,0.056874,0.069342,0.082354,0.090710,...,0.133621,0.136226,0.133644,0.131529,0.128927,0.126711,0.124216,0.122334,0.120818,0.120573
110,Ukraine,0.000000,0.000000,2.803289,4.026025,3.350876,2.862587,3.405167,3.651017,3.880459,...,4.955661,4.918671,4.882326,4.842851,4.806107,4.776974,4.632450,4.599541,4.574787,4.565500
111,United Arab Emirates,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.004689,0.006086,0.007736,0.009084,0.008778,0.008498,0.008241,0.008000,0.007792,0.007776
112,United Kingdom,5.135252,3.932735,3.469491,3.239160,3.372153,3.460411,3.296964,3.185395,3.092502,...,2.128095,2.115343,2.100741,2.087804,2.079368,2.073937,2.075108,2.076042,2.083553,2.079323
113,United States of America,29.301649,21.950932,19.253589,18.115713,18.959747,19.628969,18.748327,18.386367,18.149694,...,14.407701,14.434516,14.454869,14.505257,14.573467,14.664518,14.765984,14.884518,15.050946,15.020391
114,Uruguay,0.000000,0.111296,0.126211,0.140682,0.161428,0.176955,0.171068,0.166161,0.162604,...,0.174806,0.176482,0.177637,0.179359,0.173309,0.175980,0.177890,0.180292,0.183495,0.183123
115,Uzbekistan,0.000000,0.000000,0.271058,0.376528,0.313385,0.267719,0.360424,0.420327,0.458606,...,0.550231,0.529618,0.531048,0.533697,0.538837,0.546767,0.556061,0.566756,0.552014,0.550893
116,Venezuela (Bolivarian Republic of),0.634767,0.531703,0.466625,0.439365,0.473441,0.404451,0.403096,0.407328,0.406581,...,0.408410,0.406790,0.402990,0.400094,0.397322,0.394670,0.390918,0.379492,0.369621,0.368871
117,Virgin Islands (USA),0.000000,0.001219,0.000708,0.000495,0.000412,0.000352,0.000286,0.000242,0.000211,...,0.001127,0.001179,0.001272,0.001344,0.001411,0.001503,0.001457,0.001415,0.001416,0.001413

In [160]:
data[data["country"] == "Republic of Korea"]

year,country,1979,1980,1981,1982,1983,1984,1985,1986,1987,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
83,Republic of Korea,0.0,0.0,0.0,0.0,0.0,0.0,0.351375,0.577042,0.733545,...,2.386466,2.499253,2.639222,2.773346,2.904253,3.005318,3.105533,3.192704,3.278909,3.272252

In [161]:
data.to_csv('../data/Dataframe_for_racing_plot_WHO_data.csv', sep=',', encoding='utf-8-sig', index=False)